name: sweetsheet
description: Show beautiful bottom sheet as confirmation dialog quickly and easily.
version: 0.1.3
homepage: https://github.com/CorneilleEdi/sweetsheet

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:  